#!/bin/bash

if [ "$#" == "0" ]; then
	F="-";
else
	F="$1"
fi
if [ "$#" -gt "1" ] || [ "$F" == "--help" ] || [ "$F" == "-h" ]; then
	echo "Usage: $0 [md5sum-file]"
	exit 1
fi
CMD="md5sum"
if which ionice >/dev/null; then
	CMD="ionice -c 3 $CMD"
fi
if which nice >/dev/null; then
	CMD="nice -n 19 $CMD"
fi
($CMD -c $F && echo 'All OK')|grep -vE ': OK$'
exit ${PIPESTATUS[0]}
